[package]
name = "ring-aes-encrypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.1"
dotenv = "0.15.0"
ring = "0.17.7"
